# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import common_pb2 as proto_dot_common__pb2


class CommonStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Request = channel.unary_unary(
        '/pbcommon.Common/Request',
        request_serializer=proto_dot_common__pb2.Req.SerializeToString,
        response_deserializer=proto_dot_common__pb2.Resp.FromString,
        )
    self.Login = channel.unary_unary(
        '/pbcommon.Common/Login',
        request_serializer=proto_dot_common__pb2.LoginReq.SerializeToString,
        response_deserializer=proto_dot_common__pb2.LoginResp.FromString,
        )
    self.Download = channel.unary_unary(
        '/pbcommon.Common/Download',
        request_serializer=proto_dot_common__pb2.DownloadReq.SerializeToString,
        response_deserializer=proto_dot_common__pb2.DownloadResp.FromString,
        )
    self.Update = channel.unary_unary(
        '/pbcommon.Common/Update',
        request_serializer=proto_dot_common__pb2.UpdateReq.SerializeToString,
        response_deserializer=proto_dot_common__pb2.DownloadResp.FromString,
        )
    self.UpdateIP = channel.unary_unary(
        '/pbcommon.Common/UpdateIP',
        request_serializer=proto_dot_common__pb2.UpdateIPReq.SerializeToString,
        response_deserializer=proto_dot_common__pb2.UpdateIPResp.FromString,
        )
    self.ReqToolInfo = channel.unary_unary(
        '/pbcommon.Common/ReqToolInfo',
        request_serializer=proto_dot_common__pb2.ToolReq.SerializeToString,
        response_deserializer=proto_dot_common__pb2.ToolInfoResp.FromString,
        )
    self.DownloadRecord = channel.unary_unary(
        '/pbcommon.Common/DownloadRecord',
        request_serializer=proto_dot_common__pb2.DownloadRecordReq.SerializeToString,
        response_deserializer=proto_dot_common__pb2.Resp.FromString,
        )


class CommonServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateIP(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReqToolInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommonServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Request': grpc.unary_unary_rpc_method_handler(
          servicer.Request,
          request_deserializer=proto_dot_common__pb2.Req.FromString,
          response_serializer=proto_dot_common__pb2.Resp.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=proto_dot_common__pb2.LoginReq.FromString,
          response_serializer=proto_dot_common__pb2.LoginResp.SerializeToString,
      ),
      'Download': grpc.unary_unary_rpc_method_handler(
          servicer.Download,
          request_deserializer=proto_dot_common__pb2.DownloadReq.FromString,
          response_serializer=proto_dot_common__pb2.DownloadResp.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=proto_dot_common__pb2.UpdateReq.FromString,
          response_serializer=proto_dot_common__pb2.DownloadResp.SerializeToString,
      ),
      'UpdateIP': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateIP,
          request_deserializer=proto_dot_common__pb2.UpdateIPReq.FromString,
          response_serializer=proto_dot_common__pb2.UpdateIPResp.SerializeToString,
      ),
      'ReqToolInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ReqToolInfo,
          request_deserializer=proto_dot_common__pb2.ToolReq.FromString,
          response_serializer=proto_dot_common__pb2.ToolInfoResp.SerializeToString,
      ),
      'DownloadRecord': grpc.unary_unary_rpc_method_handler(
          servicer.DownloadRecord,
          request_deserializer=proto_dot_common__pb2.DownloadRecordReq.FromString,
          response_serializer=proto_dot_common__pb2.Resp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pbcommon.Common', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
